apiVersion: v1
data:
  username: a2V5Y2xvYWsK 
  password: UEBzc3cwcmRQQHNzdzByZAo=
kind: Secret
metadata:
  name: keycloak-cred
  # namespace: pgdb
  namespace: keycloak
  labels:
    cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
